### PR TITLE
RPM package and MIN / MAX commands for MPL

### PR DESCRIPTION
**Pull request by davy7125**
Executing jorgan-rpm-package/build.sh creates a rpm package that can be installed on Fedora
Tested on Fedora 35

### CODE REVIEW

**Comment by svenmeier** [comment]
Thanks, I will check this asap.

**Comment by davy7125** [comment]
I also added two commands for the MPL language: min and max. I tried to make another pull request but it's like everything has been put together, with the RPM package.

To describe my need of min / max, here is the messages of a continuous filter I'm using:
```
engaging: set 176, set 19, set stopLoad | mult keyLoad | mult 127 | min 127
intercept: equal 176, equal 20, div 12 | get keyLoad
intercept: equal 176, equal 21, div 80 | get stopLoad
```
The multiplication of stopLoad by keyLoad possibly results in a value exceeding 1.0f (this is intentional), and after another multiplication by 127 I need to limit it to 127 otherwise it will be rejected in CC 19.
- X min Y means: the minimum of X and Y will be retained
- X max Y means: the maximum of X and Y will be retained

**Comment by svenmeier** [comment]
I would find it more intuitive when min and max are switched:

    engaging: set 176, set 19, set stopLoad | mult keyLoad | mult 127 | max 127

i.e. "limit the value to maximum of 127". WDYT?

**Comment by davy7125** [comment]
You are right, this is reversed.
Mathematically this is a bit less logical but what matters how we understand the part "... | max 127".
min and max can be considered as limits

**Review by svenmeier — APPROVED** [review]
Great, thanks!

**Pull request merged**
