### PR TITLE
Menu and settings reorder + french translation

### PR DESCRIPTION
**Pull request by davy7125**

### CODE REVIEW

**Comment by svenmeier** [comment]
Could you please split this PR into two, so that we can merge the language changes first?

I haven't had time to look at the menu changes and its implications.

**Comment by davy7125** [comment]
> Could you please split this PR into two, so that we can merge the language changes first?
> 
> I haven't had time to look at the menu changes and its implications.

Unfortunately the new translations take the menu modifications into account. You will have to check the menus first (2 first commits) and then the translations will be appropriate.
Nothing surprising in the menus refactoring, just a better compliance to the actual standards.

**Comment by svenmeier** [comment]
I don't have time to review the menu changes

**Comment by davy7125** [comment]
Can I help in providing screenshots? This is too bad to see these GUI improvements so quickly cleared.

**Pull request closed without merging**
